[main]
include=~/.config/fuzzel/catppuccin-mocha/sapphire.ini
namespace=fuzzel
# This size minimizes Fuzzel's one-frame resize at the 1.25 monitor scale.
font=JetBrainsMono-Regular:size=22
dpi-aware=no
prompt="❯❯ "
terminal=foot

lines=14
width=40
tabs=4
horizontal-pad=50
vertical-pad=18
inner-pad=10

image-size-ratio=.25

[border]
width=3
radius=20
