#!/usr/bin/env bash

PID=$(hyprctl clients | rg -A 8 'workspace: 7' | rg pid | cut -d ' ' -f 2)
CURRENTWORKSPACE=$(hyprctl activeworkspace | rg workspace | cut -d ' ' -f 3)
WINDOW=$(hyprctl activeworkspace | rg 'windows:'| cut -d ' ' -f 2)

if [[ $WINDOW = 1 ]]; then
	hyprctl dispatch movetoworkspace "$CURRENTWORKSPACE",pid:"$PID"
	hyprctl dispatch swapwindow r
	echo "$PID" > ~/.config/hypr/scripts/PID7
else
	ID=$(cat ~/.config/hypr/scripts/PID7)
	hyprctl dispatch movetoworkspacesilent 7,pid:"$ID"
	rm ~/.config/hypr/scripts/PID7
fi
