#!/usr/bin/env bash

PID=$(hyprctl clients | rg -A 8 'workspace: 2' | rg pid | cut -d ' ' -f 2)
CURRENTWORKSPACE=$(hyprctl activeworkspace | rg workspace | cut -d ' ' -f 3)
WINDOW=$(hyprctl activeworkspace | rg 'windows:'| cut -d ' ' -f 2)

if [[ $WINDOW = 1 && $CURRENTWORKSPACE != 2 ]]; then
	hyprctl dispatch movetoworkspace "$CURRENTWORKSPACE",pid:"$PID"
	if [[ $CURRENTWORKSPACE -lt 2 ]]; then
		hyprctl dispatch swapwindow r
	elif [[ $CURRENTWORKSPACE -gt 2 ]]; then
		hyprctl dispatch swapwindow l
	fi
	echo "$PID" > ~/.config/hypr/scripts/PID2
elif [[ $CURRENTWORKSPACE != 2 ]]; then
	ID=$(cat ~/.config/hypr/scripts/PID2)
	hyprctl dispatch movetoworkspacesilent 2,pid:"$ID"
	rm ~/.config/hypr/scripts/PID2
fi
