#!/usr/bin/env bash

CURRENTWORKSPACE=$(hyprctl activeworkspace | grep workspace | cut -d ' ' -f 3)
WINDOW=$(hyprctl activeworkspace | grep 'windows:'| cut -d ' ' -f 2)

if [[ $WINDOW = 1 ]]; then
	hyprctl dispatch movetoworkspacesilent $CURRENTWORKSPACE,'class:^(foot)$'
	hyprctl dispatch swapwindow r
else
	hyprctl dispatch movetoworkspacesilent  special:scratchpad,'class:^(foot)$'
fi
