#!/bin/sh

iDIR="$HOME/.config/mako/icons"

# Get the brightness percentage
bright=$(brightnessctl -m -d intel_backlight | cut -d, -f4 | tr -d %)

notify-send -i "$iDIR/computer.png" -t 1000 -a 'wp-bright' -h string:x-canonical-private-synchronous:bright -h int:value:$bright "Brightness: ${bright}%"
