(with-eval-after-load 'dired
  (bind-key "e" 'wdired-change-to-wdired-mode dired-mode-map)
  (defun my/dropbox ()
    (interactive)
    (find-file "~/Dropbox/"))
  (defun my/downloads ()
    (interactive)
    (find-file "~/Downloads/"))
  (defun my/githubimage ()
    (interactive)
    (find-file "~/Pictures/image/")))
