(setq easy-hugo-basedir "~/src/gitlab.com/masasam/blog/")
(setq easy-hugo-sshdomain "blogdomain")
(setq easy-hugo-root "/home/blog/")
(setq easy-hugo-previewtime "300")
(define-key global-map (kbd "C-c C-e") 'easy-hugo)
(setq easy-hugo-asciidoc-extension "adoc")
(setq easy-hugo-url "https://example.com")
(setq easy-hugo-amazon-s3-bucket-name "masasam")
(setq easy-hugo-google-cloud-storage-bucket-name "masa-storage")

(setq easy-hugo-blog-number 3)
(setq easy-hugo-basedir-1 "~/src/github.com/masasam/ppap/")
(setq easy-hugo-url-1 "http://example1.com/")
(setq easy-hugo-basedir-2 "~/src/github.com/masasam/ppap2/")
(setq easy-hugo-url-2 "http://example2.com/")

(setq easy-hugo--sort-char-flg 1)
(setq easy-hugo--sort-time-flg nil)
