(setq easy-hugo-basedir "~/src/github.com/masasam/ppap/")
(setq easy-hugo-sshdomain "blogdomain")
(setq easy-hugo-root "/home/ppap/")
(setq easy-hugo-previewtime "300")
(define-key global-map (kbd "C-c C-e") 'easy-hugo)
