(require 'bind-key)
(bind-key "C-c l" 'helm-phalcon)
(bind-key "C-c C-l" 'helm-phalcon)
(setq helm-phalcon-controllers "app/modules/frontend/controllers")
(setq helm-phalcon-services "app/models/services/Service")
(setq helm-phalcon-repositories "app/models/repositories/Repository")
(setq helm-phalcon-entities "app/models/entities")
(setq helm-phalcon-criterias "app/models/criterias")
(setq helm-phalcon-messages "app/messages")
(setq helm-phalcon-forms "app/utils/Forms")
(setq helm-phalcon-views "app/modules/frontend/views")
(setq helm-phalcon-config "app/config")
(setq helm-phalcon-util "app/utils")
(setq helm-phalcon-public "public")
