(setq easy-jekyll-basedir "~/src/github.com/masasam/jekyll/")
(setq easy-jekyll-url "https://example.org")
(setq easy-jekyll-sshdomain "blogdomain")
(setq easy-jekyll-root "/home/jekyll/")
(setq easy-jekyll-previewtime "300")
(define-key global-map (kbd "C-c C-j") 'easy-jekyll)
