;;; init.el --- init.el
;;; Commentary:
;; URL: https://github.com/masasam/dotfiles
;;; Code:
;; Package-Requires: ((emacs "25.1"))
;;(setq debug-on-error t)

(menu-bar-mode 0)
(tool-bar-mode 0)
(scroll-bar-mode 0)
(setq inhibit-splash-screen t)
(setq inhibit-startup-message t)
(set-frame-parameter nil 'fullscreen 'maximized)
(setq byte-compile-warnings '(cl-functions))

(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives '("gnu" . (concat proto "://elpa.gnu.org/packages/")))))

(package-initialize)


;; A workaround for a bug that occurs with gnutls 3.6 and emacs 26.1 emacs 26.2
(when (and (= emacs-major-version 26) (or (= emacs-minor-version 1) (= emacs-minor-version 2)))
  (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3"))


;; When emacs for the first time execute only, automatic package install
(unless (file-directory-p "~/.emacs.d/elpa")
  (package-refresh-contents)
  (package-install 'ace-window)
  (package-install 'aggressive-indent)
  (package-install 'alarm-clock)
  (package-install 'auto-compile)
  (package-install 'avy)
  (package-install 'beginend)
  (package-install 'bind-key)
  (package-install 'browse-at-remote)
  (package-install 'cape)
  (package-install 'catppuccin-theme)
  ;; (package-install 'company)
  ;; (package-install 'company-prescient)
  ;; (package-install 'company-quickhelp)
  ;; (package-install 'company-restclient)
  (package-install 'consult)
  (package-install 'consult-ghq)
  (package-install 'copilot)
  (package-install 'corfu)
  (package-install 'counsel)
  (package-install 'counsel-tramp)
  (package-install 'csv-mode)
  (package-install 'dashboard)
  (package-install 'dmacro)
  (package-install 'deadgrep)
  (package-install 'difftastic)
  (package-install 'diff-hl)
  (when (< emacs-major-version 29)
    (package-install 'docker-tramp))
  (package-install 'dockerfile-mode)
  (package-install 'dracula-theme)
  (package-install 'dumb-jump)
  (package-install 'easy-hugo)
  (package-install 'easy-jekyll)
  (package-install 'edit-indirect)
  (when (< emacs-version 27)
	(package-install 'editorconfig))
  (package-install 'editorconfig-generate)
  (when (< emacs-major-version 29)
    (package-install 'eglot))
  (package-install 'eldoc-box)
  (package-install 'elisp-slime-nav)
  (package-install 'elixir-mode)
  (package-install 'ellama)
  (package-install 'embark)
  (package-install 'embark-consult)
  (package-install 'espy)
  (package-install 'exec-path-from-shell)
  (package-install 'expand-region)
  (package-install 'fill-column-indicator)
  (package-install 'flymake)
  (package-install 'flymake-diagnostic-at-point)
  (package-install 'flyspell-correct)
  (package-install 'flyspell-correct-ivy)
  (package-install 'ggtags)
  (package-install 'git-timemachine)
  (package-install 'github-explorer)
  (package-install 'github-review)
  (package-install 'go-mode)
  (package-install 'google-c-style)
  (package-install 'google-this)
  (package-install 'google-translate)
  (package-install 'gptel)
  (package-install 'htmlize)
  (package-install 'hydra)
  (package-install 'iedit)
  (package-install 'imenu-anywhere)
  (package-install 'inf-ruby)
  (package-install 'inflections)
  (package-install 'init-loader)
  (package-install 'ivy)
  (package-install 'ivy-prescient)
  (package-install 'ivy-xref)
  (package-install 'ivy-yasnippet)
  (package-install 'js2-mode)
  (package-install 'json-mode)
  (package-install 'json-reformat)
  (package-install 'json-snatcher)
  (package-install 'jsonrpc)
  (package-install 'key-chord)
  (package-install 'keycast)
  (package-install 'keypression)
  (package-install 'keychain-environment)
  (package-install 'know-your-http-well)
  (package-install 'kubernetes)
  (package-install 'let-alist)
  (package-install 'load-relative)
  (package-install 'loc-changes)
  (package-install 'lsp-mode)
  (package-install 'lsp-pyright)
  (package-install 'lv)
  (package-install 'macrostep)
  (package-install 'magit)
  (package-install 'magit-popup)
  (package-install 'marginalia)
  (package-install 'markdown-mode)
  (package-install 'markdown-toc)
  (package-install 'material-theme)
  (package-install 'minions)
  (package-install 'nginx-mode)
  (package-install 'nodejs-repl)
  (package-install 'openwith)
  (package-install 'orderless)
  (package-install 'org)
  ;; (package-install 'package-lint)
  ;; (package-install 'package-lint-flymake)
  (package-install 'page-break-lines)
  (package-install 'pass)
  (package-install 'password-generator)
  (package-install 'pcre2el)
  (package-install 'php-mode)
  (package-install 'pkg-info)
  (package-install 'pkgbuild-mode)
  (package-install 'popup)
  (package-install 'pos-tip)
  (package-install 'posframe)
  (package-install 'prescient)
  (package-install 'projectile)
  (package-install 'projectile-rails)
  (package-install 'puni)
  (package-install 'python-mode)
  (package-install 'quickrun)
  (package-install 'rake)
  (package-install 'realgud)
  (package-install 'realgud-byebug)
  (package-install 'reformatter)
  (package-install 'repl-toggle)
  (package-install 'request)
  (package-install 'restclient)
  (package-install 'restclient-test)
  (package-install 'rg)
  (package-install 'rspec-mode)
  (package-install 'rust-mode)
  (package-install 's)
  (package-install 'scss-mode)
  (package-install 'slim-mode)
  (package-install 'sly)
  (package-install 'sly-macrostep)
  (package-install 'smart-jump)
  (package-install 'shackle)
  (package-install 'swiper)
  (package-install 'symbol-overlay)
  (package-install 'terraform-mode)
  (package-install 'test-simple)
  (package-install 'tldr)
  (package-install 'toml-mode)
  (package-install 'trashed)
  (package-install 'transient)
  (package-install 'tree-sitter)
  (package-install 'tree-sitter-langs)
  (package-install 'typescript-mode)
  (package-install 'vertico)
  (package-install 'visual-regexp)
  (package-install 'volatile-highlights)
  (package-install 'vundo)
  (package-install 'web-mode)
  (package-install 'wgrep)
  (package-install 'wgrep-ag)
  (package-install 'with-editor)
  (package-install 'yaml-mode)
  (package-install 'yasnippet)
  (package-install 'yasnippet-snippets)
  (package-install 'zeal-at-point))

;; auto-compile
(setq load-prefer-newer t)
(auto-compile-on-load-mode)
(auto-compile-on-save-mode)

;; init-loader
(custom-set-variables
 '(init-loader-show-log-after-init 'error-only))
(init-loader-load)
(setq custom-file (locate-user-emacs-file "custom.el"))

(provide 'init)
;;; init.el ends here
(put 'dired-find-alternate-file 'disabled nil)
