[env]
_.file = { path = "~/.config/mise/secrets.toml", redact = true }

[tools]
atlas = "1.3.0"
aws-cli = { version = "2.37.7", symlink_bins = "true" }
bun = "1.4.2"
cf = "8.19.0"
claude-code = "2.1.286"
codex = "0.159.3"
deno = "2.9.7"
duckdb = "1.5.6"
erlang = "29.1.1"
elixir = "1.20.4-otp-29"
elixir-ls = { version = "0.31.1", symlink_bins = "true" }
firebase = "15.32.1"
gcloud = "587.0.0"
gemini-cli = { version = "0.62.0", allow_builds = ["@github/keytar", "node-pty"] }
herdr = "0.9.3"
hugo = "0.167.0"
kind = "0.33.0"
lua-language-server = "3.19.1"
marp-cli = "4.5.1"
node = "26.10.0"
"npm:@github/copilot" = "1.0.90"
"npm:@github/copilot-language-server" = "1.551.2"
"npm:@googleworkspace/cli" = "0.22.5"
"npm:oxlint" = "1.86.0"
"npm:playwright" = "1.63.0"
"npm:pnpm" = "12.8.1"
"npm:ts-node" = "10.9.2"
"npm:typescript" = "7.0.2"
opencode = "1.18.34"
pi = "0.99.2"
ruff = "0.16.9"
stripe-cli = "1.53.0"
trdsql = "1.2.3"
uv = "0.12.21"
yay = "13.0.1"
youtube-dl = "2025.11.26"
zls = "0.16.0"
"npm:@agentclientprotocol/codex-acp" = "2.1.0"
