[env]
_.file = { path = "~/.config/mise/secrets.toml", redact = true }

[tools]
atlas = "1.3.0"
aws-cli = { version = "2.36.41", symlink_bins = "true" }
bun = "1.4.2"
claude-code = "2.1.266"
codex = "0.153.4"
deno = "2.9.6"
duckdb = "1.5.5"
erlang = "29.0.6"
elixir = "1.20.4-otp-29"
elixir-ls = { version = "0.31.1", symlink_bins = "true" }
firebase = "15.29.0"
gcloud = "583.0.0"
gemini-cli = { version = "0.59.0", allow_builds = ["@github/keytar", "node-pty"] }
herdr = "0.9.0"
hugo = "0.165.0"
kind = "0.33.0"
lua-language-server = "3.19.1"
marp-cli = "4.5.1"
node = "26.8.1"
"npm:@github/copilot" = "1.0.83"
"npm:@github/copilot-language-server" = "1.544.0"
"npm:@googleworkspace/cli" = "0.22.5"
"npm:oxlint" = "1.82.0"
"npm:playwright" = "1.63.0"
"npm:pnpm" = "12.3.4"
"npm:ts-node" = "10.9.2"
"npm:typescript" = "7.0.2"
opencode = "1.18.30"
pi = "0.85.1"
ruff = "0.16.6"
stripe-cli = "1.50.10"
trdsql = "1.2.3"
uv = "0.12.11"
yay = "13.0.1"
youtube-dl = "2025.11.26"
zls = "0.16.0"
"npm:@agentclientprotocol/codex-acp" = "1.10.0"
